-- ====================================================================
-- Class Work Scheduler: Supabase PostgreSQL Schema & Seed Data
-- ====================================================================
-- Instructions:
-- 1. Open your Supabase Dashboard: https://supabase.com/dashboard
-- 2. Go to the "SQL Editor" in the left sidebar.
-- 3. Click "New Query", paste this entire script, and click "Run".
-- ====================================================================

-- 1. DROP EXISTING TABLES (Safe reset if re-running)
DROP TABLE IF EXISTS task_completions CASCADE;
DROP TABLE IF EXISTS classworks CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. CREATE USERS TABLE
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  roll_number TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  password TEXT NOT NULL, -- Stored password or hash
  role TEXT NOT NULL CHECK (role IN ('admin', 'student')),
  section TEXT NOT NULL DEFAULT 'CSE-A',
  year INTEGER DEFAULT 3,
  department TEXT DEFAULT 'Computer Science & Engineering',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. CREATE CLASSWORKS TABLE
CREATE TABLE classworks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subject TEXT NOT NULL,
  faculty_name TEXT NOT NULL,
  description TEXT,
  target_section TEXT NOT NULL DEFAULT 'CSE-A', -- e.g., 'CSE-A' or 'ALL'
  category TEXT DEFAULT 'Assignment', -- 'Assignment', 'Lab Task', 'Project Work', 'Homework', 'Seminar'
  priority TEXT DEFAULT 'Medium', -- 'Urgent', 'High', 'Medium', 'Normal'
  due_date TIMESTAMPTZ NOT NULL,
  resource_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. CREATE TASK COMPLETIONS TABLE
CREATE TABLE task_completions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classwork_id BIGINT NOT NULL REFERENCES classworks(id) ON DELETE CASCADE,
  student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  student_roll_number TEXT NOT NULL,
  student_name TEXT NOT NULL,
  student_section TEXT NOT NULL,
  notes TEXT,
  completed_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(classwork_id, student_id)
);

-- 5. ENABLE ROW LEVEL SECURITY (RLS) & ALLOW ACCESS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE classworks ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_completions ENABLE ROW LEVEL SECURITY;

-- Allow anon public access for frontend app queries
CREATE POLICY "Public full access to users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access to classworks" ON classworks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access to task_completions" ON task_completions FOR ALL USING (true) WITH CHECK (true);

-- ====================================================================
-- SEED INITIAL DEMO DATA
-- ====================================================================

-- Insert Admin Account
INSERT INTO users (roll_number, name, password, role, section, year, department)
VALUES 
  ('admin', 'Faculty Coordinator / Admin', 'admin123', 'admin', 'ALL', NULL, 'Academic Affairs');

-- Insert Sample Students for Section CSE-A
INSERT INTO users (roll_number, name, password, role, section, year, department)
VALUES 
  ('22A91A0501', 'Aarav Sharma', 'student123', 'student', 'CSE-A', 3, 'Computer Science & Engineering'),
  ('22A91A0502', 'Ananya Patel', 'student123', 'student', 'CSE-A', 3, 'Computer Science & Engineering');

-- Insert Sample Assignments for CSE-A and ALL
INSERT INTO classworks (title, subject, faculty_name, description, target_section, category, priority, due_date, resource_url)
VALUES 
  (
    'Deadlock Detection & Banker Algorithm Implementation',
    'Operating Systems',
    'Dr. K. Srinivas',
    'Implement the Banker’s Algorithm for deadlock avoidance in C/C++ or Python. Submit your source code along with 3 test matrices with safe state sequences.',
    'CSE-A',
    'Lab Task',
    'Urgent',
    NOW() + INTERVAL '1 day',
    'https://en.wikipedia.org/wiki/Banker%27s_algorithm'
  ),
  (
    'Normalization (1NF, 2NF, 3NF, BCNF) Problem Set 4',
    'Database Management Systems',
    'Prof. Sunita Nair',
    'Solve the 5 relational schema decomposition problems attached in the department portal. Clearly show functional dependencies and lossless join verification.',
    'ALL',
    'Assignment',
    'High',
    NOW() + INTERVAL '2 days',
    'https://www.geeksforgeeks.org/database-normalization-introduction/'
  ),
  (
    'Greedy vs Dynamic Programming: 0/1 Knapsack Analysis',
    'Design & Analysis of Algorithms',
    'Dr. M. Venkatesh',
    'Write a comparative analysis and benchmark report between Fractional Knapsack (Greedy) and 0/1 Knapsack (DP) algorithms for n=1000 items.',
    'CSE-A',
    'Assignment',
    'Medium',
    NOW() + INTERVAL '4 days',
    ''
  );

-- Pre-seed completions for demonstration
INSERT INTO task_completions (classwork_id, student_id, student_roll_number, student_name, student_section, notes)
SELECT 
  c.id, 
  u.id, 
  u.roll_number, 
  u.name, 
  u.section, 
  'Completed lab assignment simulation'
FROM classworks c, users u
WHERE c.title LIKE 'Deadlock Detection%' AND u.roll_number = '22A91A0501';

-- Done!
SELECT 'Supabase schema and seed data created successfully!' AS status;
