-- ====================================================================
-- Class Work Scheduler: Supabase PostgreSQL Schema & Seed Data
-- ====================================================================
-- Instructions:
-- 1. Open your Supabase Dashboard: https://supabase.com/dashboard
-- 2. Go to the "SQL Editor" in the left sidebar.
-- 3. Click "New Query", paste this entire script, and click "Run".
-- ====================================================================

-- 1. DROP EXISTING TABLES (Safe reset if re-running)
DROP TABLE IF EXISTS task_completions CASCADE;
DROP TABLE IF EXISTS classworks CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS sections CASCADE;

-- 2. CREATE SECTIONS TABLE
CREATE TABLE sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. CREATE USERS TABLE
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  roll_number TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  password TEXT NOT NULL, -- Stored password or hash
  role TEXT NOT NULL CHECK (role IN ('admin', 'student')),
  section TEXT NOT NULL DEFAULT 'CSE-A',
  year INTEGER DEFAULT 3,
  department TEXT DEFAULT 'Computer Science & Engineering',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. CREATE CLASSWORKS TABLE
CREATE TABLE classworks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subject TEXT NOT NULL,
  faculty_name TEXT NOT NULL,
  description TEXT,
  target_section TEXT NOT NULL DEFAULT 'CSE-A', -- e.g., 'CSE-A' or 'ALL'
  category TEXT DEFAULT 'Assignment', -- 'Assignment', 'Lab Task', 'Project Work', 'Homework', 'Seminar'
  priority TEXT DEFAULT 'Medium', -- 'Urgent', 'High', 'Medium', 'Normal'
  due_date TIMESTAMPTZ NOT NULL,
  resource_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. CREATE TASK COMPLETIONS TABLE
CREATE TABLE task_completions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classwork_id BIGINT NOT NULL REFERENCES classworks(id) ON DELETE CASCADE,
  student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  student_roll_number TEXT NOT NULL,
  student_name TEXT NOT NULL,
  student_section TEXT NOT NULL,
  notes TEXT,
  completed_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(classwork_id, student_id)
);

-- 6. ENABLE ROW LEVEL SECURITY (RLS) & ALLOW ACCESS
ALTER TABLE sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE classworks ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_completions ENABLE ROW LEVEL SECURITY;

-- Allow anon public access for frontend app queries
CREATE POLICY "Public full access to sections" ON sections FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access to users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access to classworks" ON classworks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access to task_completions" ON task_completions FOR ALL USING (true) WITH CHECK (true);

-- ====================================================================
-- SEED: Admin Account Only
-- ====================================================================

-- Insert Admin Account
INSERT INTO users (roll_number, name, password, role, section, year, department)
VALUES 
  ('admin', 'Faculty / Admin', 'admin123', 'admin', 'ALL', NULL, 'Academic Affairs')
ON CONFLICT (roll_number) DO NOTHING;

-- Done!
SELECT 'Supabase schema created successfully. Log in as admin / admin123 to get started.' AS status;

